name: ci-build
on: [push, pull_request]

jobs:
  run-next-build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up repository
        uses: actions/checkout@master

      - name: Set up repository
        uses: actions/checkout@master
        with:
          ref: master

      - name: Merge to master branch
        run: git checkout --progress --force ${{ github.sha }}

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 'Restore Cache'
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            gray-app/.next/cache
            gray-app/node_modules
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: 'Install Packages'
        run: 'cd gray-app && npm i'
      
      - name: 'Run build'
        run: cd gray-app && npm run build
